apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aep.name" . }}-api
  labels: {{- include "aep.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels: {{- include "aep.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: api
          image: {{ include "aep.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env: {{- include "aep.env" . | nindent 12 }}
          readinessProbe:
            httpGet: {path: /healthz, port: {{ .Values.api.port }}}
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /healthz, port: {{ .Values.api.port }}}
            periodSeconds: 15
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: "1", memory: 512Mi}
          securityContext: {{- include "aep.containerSecurity" . | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aep.name" . }}-api
  labels: {{- include "aep.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
