apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aep.name" . }}-secrets
  labels: {{- include "aep.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "aep.databaseUrl" . | quote }}
